### ISSUE TITLE
ImportError: No module named helper  / OS centos 7

### ISSUE THREAD

**Issue by smowtion** [bachvtuan/Backup-To-Google-Drive#1]
[root@localhost ~]# python backup.py root/configs/config.json /home
Traceback (most recent call last):
  File "backup.py", line 21, in <module>
    import helper
ImportError: No module named helper

**Comment by Blacksmoke16** [comment]
You need to also have the helper.py file in the same directory

**Comment by bachvtuan** [comment]
Closed
