### ISSUE TITLE
CentOS 6 and Python 2.6.6

### ISSUE THREAD

**Issue by tangduongtrieu** [bachvtuan/Backup-To-Google-Drive#2]
Upload file .zip -> normal
Upload file .sql.gz -> An error occured: <HttpError 400 "Media type 'None' is not supported. Valid media types: [*/*]">

**Comment by bachvtuan** [comment]
Hi. 
At first please upgrade python to the latests stable version is 2.7.6.
The second thing is can provide more detail such as your script when you were making the backup.
I don't know what happened with poor information.

Thank !

**Comment by tangduongtrieu** [comment]
Sorrry github remove my code.
Upload file .sql.gz -> An error occured: HttpError 400 "Media type 'None' is not supported. Valid media types: [ \* / *]

Content File backups.

mysqldump --single-transaction --routines --triggers --add-drop-table --extended-insert -u username -h 127.0.0.1 -p'passs' databasen | gzip -9 > /var/backups/$(date +"%Y-%m-%d")/mywebsite.com/mywebsite_$(date +"%Y-%m-%d").sql.gz

python /root/configs/backup.py /root/configs/config.json /var/backups/$(date +"%Y-%m-%d")/mywebsite.com/mywebsite_$(date +"%Y-%m-%d").sql.gz

**Comment by bachvtuan** [comment]
I have justed test .sql.gz and it worked well without any error.
![result](http://i1105.photobucket.com/albums/h360/bvtuan/image%20web/Screenshot-geekubuntu%20-Downloads-Backup-To-Google-Drive-master-1_zpsg0r2wmdm.png)
I think the your dump database code can be wrong, make sure check size of dump file path 

```
var/backups/$(date +"%Y-%m-%d")/mywebsite.com/mywebsite_$(date +"%Y-%m-%d").sql.gz 
```

must greater than 0byte.

**Comment by tangduongtrieu** [comment]
yes!
error only CentOS 6 and python 2.6.6
i run it on CentOS 7, python 2.7 and working very good.

**Comment by bachvtuan** [comment]
Please upgrade to python2.7 as my recommend. Python2.7 is more stable than python 2.6.*
