### ISSUE TITLE
ImportError: cannot import name SignedJwtAssertionCredentials

### ISSUE THREAD

**Issue by foxhound87** [bachvtuan/Backup-To-Google-Drive#4]
```
Traceback (most recent call last):
  File "/backup/lib/backup.py", line 21, in <module>
    import helper
  File "/backup/lib/helper.py", line 2, in <module>
    from oauth2client.client import SignedJwtAssertionCredentials
ImportError: cannot import name SignedJwtAssertionCredentials`
```

**Comment by bachvtuan** [comment]
Hi make sure you installed 

```
easy_install --upgrade google-api-python-client
```

If it's fail, you can try install this package

```
easy_install --upgrade oauth2client
```

**Comment by foxhound87** [comment]
didn't fix the problem.

and following this: http://stackoverflow.com/questions/14063124/importerror-cannot-import-name-signedjwtassertioncredentials

when I do: pip install pycrypto
I get this error:

```
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0tdN9M/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-aa_Afz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0tdN9M/pycrypto/

```

**Comment by bachvtuan** [comment]
You may need install dependency package if you're using Ubuntu, Debian.

```
apt-get install python-dev
```

When done, You may need to install 

```
pip install pycrypto
pip install pyOpenSSL==0.12
```

**Comment by budiwijaya** [comment]
Hi, this error is because of oauth2client needs version 1.5.2
You can try to this command easy_install oauth2client==1.5.2
ref: https://github.com/google/google-api-python-client/issues/193

**Comment by bachvtuan** [comment]
@foxhound87 let me know if you can fix it by using the method from @budiwijaya .

**Comment by lordaikins** [comment]
Thanks for the wonderful code @bachvtuan. I ran into the same error and tried using **ServiceAccountCredentials** to replace the **SignedJwtAssertionCredentials**. However, I got another global name 'self' error. Then, I reverted to the original script from @bachvtuan, did _pip install oauth2client==1.5.2_ as suggested by @budiwijaya and finally did  _pip install pyopenssl_ and problem SOLVED!

**Comment by daguy666** [comment]
Google deprecated the `SignedJwtAssertionCredentials` class in favor of  the `ServiceAccountCredentials` class
- p12 work flow

``` python
from oauth2client.service_account import ServiceAccountCredentials

client_email = '1234556-blahblahblah@developer.gserviceaccount.com'
scopes = ['https://www.googleapis.com/auth/sqlservice.admin']

credentials = ServiceAccountCredentials.from_p12_keyfile(
    client_email, '/path/to/keyfile.p12', scopes=scopes)
```
- Json workflow

``` python
from oauth2client.service_account import ServiceAccountCredentials

scopes = ['https://www.googleapis.com/auth/sqlservice.admin']

credentials = ServiceAccountCredentials.from_json_keyfile_name(
    '/path/to/keyfile.json', scopes=scopes)
```
